<?php
header("Access-Control-Allow-Origin: *");
header('Content-Type: application/json');
$data = array(
	'products' => [
	 	array(
			"link" => "http://www.luxxu.net/products/liberty-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/liberty-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "liberty",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/babel-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/babel-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "babel",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/empire-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/empire-xl-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-xl-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire XL",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/scala-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/scala-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "scala",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/burj-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/burj-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "burj",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/mcqueen-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/mcqueen-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "mcqueen",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		),  
		array(
			"link" => "http://www.luxxu.net/products/waterfall-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/waterfall-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		),  
		array(
			"link" => "http://www.luxxu.net/products/theatre-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/theatre-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "theatre",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/guggenheim-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/guggenheim-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "guggenheim",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
	 	array(
			"link" => "http://www.luxxu.net/products/trump-chandelier.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/trump-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/babel-snooker-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/babel-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "babel snooker",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/babel-snooker-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/babel-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "babel snooker",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/trump-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/trump-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/majestic-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/majestic-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "majestic",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/pearl-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/pearl-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "pearl",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "http://www.luxxu.net/products/explosion-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/explosion-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "explosion",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/tycho-round-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/tycho-round-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "tycho round",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/mcqueen-round-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/mcqueen-round-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "mcqueen round",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/mcqueen-globe-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/mcqueen-globe-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "mcqueen globe",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/waterfall-suspension-round.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/waterfall-round-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "waterfall round",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/empire-suspension.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/empire-snooker.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-snooker-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire snooker",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/waterfall-suspension-rectangular.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/waterfall-rectangular-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/babel-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/babel-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "babel",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/trump-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/trump-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/pearl-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/pearl-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "pearl",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/tycho-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/tycho-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "tycho",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/mcqueen-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/mcqueen-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "mcqueen",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/burj-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/burj-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "burj",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/draycott-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/draycott-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "draycott",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "http://www.luxxu.net/products/empire-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/waterfall-pendant.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/waterfall-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/scala-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/scala-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "scala",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),  
		array(
			"link" => "http://www.luxxu.net/products/babel-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/babel-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "babel",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),   
		array(
			"link" => "http://www.luxxu.net/products/tycho-small-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/tycho-small-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "tycho small",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "http://www.luxxu.net/products/tycho-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/tycho-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "tycho",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),    
		array(
			"link" => "http://www.luxxu.net/products/liberty-wall-I.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/liberty-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "liberty I",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),      
		array(
			"link" => "http://www.luxxu.net/products/liberty-wall-II.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/liberty-II-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "liberty II",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),  
		array(
			"link" => "http://www.luxxu.net/products/waterfall-torch-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/waterfall-torch-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "waterfall torch",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "http://www.luxxu.net/products/draycott-wall-I.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/draycott-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "draycott I",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),     
		array(
			"link" => "http://www.luxxu.net/products/draycott-wall-II.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/draycott-wall-II-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "draycott II",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/burj-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/burj-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "burj",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "http://www.luxxu.net/products/empire-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),  
		array(
			"link" => "http://www.luxxu.net/products/mcqueen-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/mcqueen-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "mcqueen",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),  
		array(
			"link" => "http://www.luxxu.net/products/waterfall-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/waterfall-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "http://www.luxxu.net/products/trump-wall.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/trump-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/scala-plafond.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/scala-plafond-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "scala",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "plafond",
		    "partner" => true,
		), 
		array(
			"link" => "http://www.luxxu.net/products/empire-plafond.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/empire-plafond-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "plafond",
		    "partner" => true,
		),
		array(
			"link" => "http://www.luxxu.net/products/draycott-floor.php",
			"image"=> "http://www.luxxu.net/images/ext-campaign/partners/lamps/draycott-floor-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "http://www.luxxu.net/",
		    "name" => "draycott",
		    "category_link" => "http://www.luxxu.net/lighting/",
		    "category" => "floor-lamp",
		    "partner" => true,
		)
	]
);


echo json_encode($data);