<?php
header("Access-Control-Allow-Origin: *");
header('Content-Type: application/json');
$data = array(
	'products' => [
		array(
			"link" => "https://www.luxxu.net/products/babel-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/babel-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "babel",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "https://www.luxxu.net/products/tycho-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/tycho-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "tycho",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "https://luxxu.net/products/liberty-wall-II.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/liberty-II-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "liberty II wall",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),  
		array(
			"link" => "https://www.luxxu.net/products/tycho-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/tycho-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "tycho",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),    
		array(
			"link" => "https://www.luxxu.net/products/liberty-wall-I.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/liberty-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "liberty I",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),      
		array(
			"link" => "https://www.luxxu.net/products/liberty-wall-II.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/liberty-II-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "liberty II",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),  
		array(
			"link" => "https://www.luxxu.net/products/waterfall-torch-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/waterfall-torch-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "waterfall torch",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "https://www.luxxu.net/products/draycott-wall-I.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/draycott-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "draycott I",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => false,
		),     
		array(
			"link" => "https://www.luxxu.net/products/draycott-wall-II.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/draycott-wall-II-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "draycott II",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/burj-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/burj-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "burj",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "https://www.luxxu.net/products/empire-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/empire-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),  
		array(
			"link" => "https://www.luxxu.net/products/mcqueen-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/mcqueen-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "mcqueen",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),  
		array(
			"link" => "https://www.luxxu.net/products/waterfall-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/waterfall-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		),   
		array(
			"link" => "https://www.luxxu.net/products/trump-wall.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/trump-wall-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "wall-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/draycott-floor.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/other-lamps/draycott-floor-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "draycott",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "floor-lamp",
		    "partner" => true,
		)
	]
);


echo json_encode($data);