<?php
header("Access-Control-Allow-Origin: *");
header('Content-Type: application/json');
$data = array(
	'products' => [
	 	array(
			"link" => "https://www.luxxu.net/products/majestic-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/majestic-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "majestic",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/majestic-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/majestic-II-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "majestic II",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		), 
	 	array(
			"link" => "https://www.luxxu.net/products/liberty-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/liberty-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "liberty",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/babel-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/babel-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "babel",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/empire-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/empire-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/empire-xl-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/empire-xl-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire XL",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/scala-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/scala-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "scala",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/burj-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/burj-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "burj",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/mcqueen-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/mcqueen-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "mcqueen",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		),  
		array(
			"link" => "https://www.luxxu.net/products/waterfall-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/waterfall-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		),  
		array(
			"link" => "https://www.luxxu.net/products/theatre-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/theatre-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "theatre",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/guggenheim-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/guggenheim-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "guggenheim",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => false,
		), 
	 	array(
			"link" => "https://www.luxxu.net/products/trump-chandelier.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/trump-chandelier-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "chandelier",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/babel-snooker-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/babel-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "babel snooker",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/babel-snooker-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/babel-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "babel snooker",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/trump-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/trump-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/majestic-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/majestic-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "majestic",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/pearl-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/pearl-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "pearl",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/explosion-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/explosion-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "explosion",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/tycho-round-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/tycho-round-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "tycho round",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/mcqueen-round-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/mcqueen-round-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "mcqueen round",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/mcqueen-globe-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/mcqueen-globe-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "mcqueen globe",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => true,
		),
		array(
			"link" => "https://www.luxxu.net/products/waterfall-suspension-round.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/waterfall-round-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "waterfall round",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/empire-suspension.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/empire-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/empire-snooker.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/empire-snooker-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire snooker",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/waterfall-suspension-rectangular.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/waterfall-rectangular-suspension-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "suspension-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/babel-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/babel-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "babel",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/trump-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/trump-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "trump",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/pearl-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/pearl-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "pearl",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/tycho-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/tycho-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "tycho",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/mcqueen-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/mcqueen-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "mcqueen",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/burj-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/burj-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "burj",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/draycott-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/draycott-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "draycott",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		),
		array(
			"link" => "https://www.luxxu.net/products/empire-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/empire-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => false,
		), 
		array(
			"link" => "https://www.luxxu.net/products/waterfall-pendant.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/waterfall-pendant-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "waterfall",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "pendant-lamp",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/scala-plafond.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/scala-plafond-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "scala",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "plafond",
		    "partner" => true,
		), 
		array(
			"link" => "https://www.luxxu.net/products/empire-plafond.php",
			"image"=> "https://www.luxxu.net/images/ext-campaign/partners/suspension-lamps/empire-plafond-luxxu.jpg",
			"brand" => "luxxu",
		    "brand_link" => "https://www.luxxu.net/",
		    "name" => "empire",
		    "category_link" => "https://www.luxxu.net/lighting/",
		    "category" => "plafond",
		    "partner" => true,
		),
	]
);


echo json_encode($data);